openapi: '3.1.0'
info:
  title: 'Task API'
  description: 'A simple Node.js + Express + Prisma API for managing tasks'
  version: '1.0.0'
servers:
  - url: http://localhost:3000
    description: 'Local Development server'
  - url: https://task-api-7944.onrender.com
    description: 'Production server on render'
paths:
  /tasks:
    $ref: paths/tasks.yaml
components:
  schemas:
    Task:
      $ref: components/schemas/Task.yaml